#!/bin/zsh

echo "\n"
echo -e "\e[0;31mFINDING FILES...\033[0m"
echo "\n"

for current in `cat files.txt`; do
    find . -name $current -type f
done

for current in `cat folders.txt`; do
    find . -name "$current" -type d
done

echo "\n"
echo -e "\e[0;32mWOULD YOU LIKE TO ERASE IT?\033[0m"
echo "\n"